apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 1 
  template: 
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:7.9.2
        env:
        - name: discovery.type
          value: single-node
        - name: xpack.monitoring.enabled
          value: "true"
        - name: xpack.watcher.enabled
          value: "false"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        
        resources:
          requests:
            memory: 1Gi
            cpu: "250m"
          limits:
            memory: 1Gi
            cpu: "500m"
        ports:
        - containerPort: 9200
        - containerPort: 9300
        
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector: 
    app: elasticsearch
  type: NodePort  
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 31200
