apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api-deployment
  labels:
    app: catalog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
        - name: catalog-api
          image: eshopacr.azurecr.io/catalogapi:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: mongo-configmap
                    key: connection_string
            - name: DatabaseSettings__DatabaseName
              valueFrom:
                  configMapKeyRef:
                    name: mongo-configmap
                    key: DatabaseName
            - name: DatabaseSettings__CollectionName
              valueFrom:
                  configMapKeyRef:
                    name: mongo-configmap
                    key: CollectionName
            - name: ElasticConfiguration__Uri
              valueFrom:
                  configMapKeyRef:
                    name: mongo-configmap
                    key: ElasticSetting
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-api-service
spec:
  type: LoadBalancer
  selector:
    app: catalog-api
  ports:
    - protocol: TCP
      port: 80