apiVersion: v1
kind: ConfigMap
metadata:
  name: ordering-api-configmap
  labels:
    app: ordering-api
data:
  connection_string: Server=mssql-service;Database=OrderDb;User Id=sa;Password=MyC0m9l&xP@ssw0rd;
  ElasticSetting: http://elasticsearch:9200
  EventBusSettings__HostAddress: amqp://guest:guest@rabbit-mq-service:5672