apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-api-deployment
  labels:
    app: basket-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basket-api
  template:
    metadata:
      labels:
        app: basket-api
    spec:
      containers:
        - name: basket-api
          image: rahulsahay19/basketapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: CacheSettings__ConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: cache-configmap
                    key: connection_string
            - name: GrpcSettings__DiscountUrl
              valueFrom:
                  configMapKeyRef:
                    name: grpc-configmap
                    key: DiscountUrl
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: basket-api-service
spec:
  type: NodePort
  selector:
    app: basket-api
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 80
      nodePort: 31001